### ISSUE TITLE
ITS NOT SAFE!

### ISSUE THREAD

**Issue by KGROUPS-GITHUB** [CodeWithKhush/WEATHER-NOW#1]
# HEY @CodeWithKhush 
## WHEN I WAS INSTALLING IT, GOOGLE PLAY PROTECT DIALOGUE APPEARED.

**Comment by CodeWithKhush** [comment]
HEY @KGROUPS-GITHUB,
ITS BECAUSE WE DO NOT HAVE GOOGLE PLAY DEVELOPER PROFILE.
PLEASE SCAN IT AND DOWNLOAD, NO ISSUE WILL BE THERE

**Comment by KGROUPS-GITHUB** [comment]
HEY ITS OKAY NOW

**Comment by CodeWithKhush** [comment]
THANKS
