### ISSUE TITLE
CAN YOU ADD MORE FEATURES!

### ISSUE THREAD

**Issue by KGROUPS-GITHUB** [CodeWithKhush/WEATHER-NOW#2]
# I WANT NEW FEATURES LIKE:

## 2. AQI

**Comment by CodeWithKhush** [comment]
HEY @KGROUPS-GITHUB, 
ITS UPLOADED TODAY ONLY SO WAIT SOME TIME.

**Comment by CodeWithKhush** [comment]
@KGROUPS-GITHUB ALSO THANKS FOR IDEA
